title: ZinZen® blog
author: Tijl Leenders
email: tijl@ZinZen.me
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  ZinZen® purpose planner blog

# social links
github_username:  tijlleenders # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
