---
title: "Welcome to the ZinZen blog"
date: 2021-09-03
---
author: Tijl Leenders
email: tijl.leenders@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  ZinZen purpose planner blog

# social links
github_username:  tijlleenders # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
